feat: "Following" button to "Unfollow" on hover
open-sauced/app pull request #1588
Opened 2023-08-22 14:00 UTC by ThePiyushAggarwal

## Description

"Following" button changed to "Unfollow" when hovered/focused on other user pages when the user is logged in.

Contributor Profile Header changes
- How? Made use of Tailwind CSS selectors in this. Two `span` tags are used, one of them is hidden based on if it is hovered or not.
- 🌟 Made the dropdown accessible. The button earlier was not getting clicked using keyboard.

Top Contributors changes
- Changed the "following" to "unfollow" when hovered/focused. Accessible with keyboard.

Fixes #1468 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1468 

## Mobile & Desktop Screenshots/Recordings

|  | Before | After |
| ---- | ---- | ---- |
| Profile Header Menu | ![image](https://user-images.githubusercontent.com/23109390/257868314-dc91d50a-065f-4fb0-8f0c-fa7f0614dae9.png) |   <video src="https://github.com/open-sauced/app/assets/27003616/64f8cce3-9ac7-4cc3-abfd-6fb065604173"  /> |
| Highlights Top Contributors Card |  ![image](https://github.com/open-sauced/app/assets/27003616/b1a4027c-7150-4281-ae01-63dcf25253bb) |  <video src="https://github.com/open-sauced/app/assets/27003616/740988a5-56df-4b64-a14c-9f72a1fbff0d"  /> |

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

2023-08-22 16:48 UTC, OgDev-01 approved these changes
Nice!, thanks for turning this around

2023-08-22 16:57 UTC, ThePiyushAggarwal commented
> Nice!, thanks for turning this around 🍕

Thank you, I’m glad I could help!

2023-08-22 20:56 UTC, jpmcb requested changes
https://github.com/open-sauced/app/assets/23109390/150754ed-bd6e-426f-85a7-5378924c6fed

This behavior is pretty inconsistent: notice in my video how it only changes when it's _directly_ over the button which feels like a sharp edge.

2023-08-22 23:38 UTC, bdougie commented
Thanks for jumping on this. We have a following button in other places that we would want to repeat this interaction. i.e. Top Contributors on the highlights page. 

![Screen Shot 2023-08-22 at 4 29 58 PM](https://github.com/open-sauced/app/assets/5713670/651fc1c9-2174-4588-bb7f-87eacb9432ec)

2023-08-23 04:01 UTC, ThePiyushAggarwal commented on components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
> +                      {/* Follow, Unfollow button */}
Shall I remove this? I have added this just for reference.

2023-08-23 04:02 UTC, ThePiyushAggarwal commented
Thanks for reviewing! I will work further on the changes mentioned.

2023-08-23 18:27 UTC, ThePiyushAggarwal commented on components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
> +                      {/* Follow, Unfollow button */}
Removed the comment.

2023-08-23 18:29 UTC, ThePiyushAggarwal commented
Hi guys! 
The PR is ready for review again. I have made some accessibility improvements as well. Please check out the updated PR description (videos too).

2023-08-23 20:53 UTC, jpmcb reviewed
👏🏼 Very nice!!! This is getting closer. I noticed a few other sharp edges:
1. When selecting "Follow" for someone on the main highlights page, the button doesn't update until I click somewhere else. It only changes to "Unfollow". Is that element not being updated properly when a follow occurs?
2. This introduces some spacing issues with the "Following" button on profiles (notice the spacing issue when the button is paired with the "Collaborate" button. It should be centered)


https://github.com/open-sauced/app/assets/23109390/48f56dc5-f155-4d02-b1ca-e6a1ef9fb81a

2023-08-23 21:00 UTC, ThePiyushAggarwal commented
Thanks for reviewing! I understand the issues. The first one is happening because the button is still in focus after clicking it. I will work on solutions, make the changes and update the PR.

2023-08-24 14:48 UTC, ThePiyushAggarwal commented
Fixed the issues pointed out [above](https://github.com/open-sauced/app/pull/1588#pullrequestreview-1592393292).

### 1. Top Contributors - "unfollow" not getting replaced with "following"
[focus-follow-button-fix.webm](https://github.com/open-sauced/app/assets/27003616/b2ede681-e033-4f59-8e2e-3f43f4bb6565)

### 2. Profile Header - Alignment issue with "Collaborate" button
[follow-button-alignment-fix.webm](https://github.com/open-sauced/app/assets/27003616/61baa256-2074-4663-a4a2-2d00b4d0e5c3)

2023-08-24 15:58 UTC, OgDev-01 commented
Nicely done @ThePiyushAggarwal 🍕🍕.

2023-08-24 15:58 UTC, OgDev-01 approved these changes

2023-08-24 17:40 UTC, jpmcb approved these changes

2023-08-24 17:50 UTC, merged

2023-08-24 17:52 UTC, ThePiyushAggarwal commented
🍕🫡🍕