fix: opening someone's profile menu locks scrollbar and "shifts" header css
open-sauced/app pull request #1704
Opened 2023-09-16 22:10 UTC by RitaDee

## Description

This PR addresses the issue of the scrollbar locking and preventing scrolling that was observed in the `ContributorProfileHeader` component. It achieves this by replacing the deprecated `DropdownMenu` component with the `Popover` component from `@radix-ui/react-popover`. Additionally, it replaces the `DropdownMenuItem` components with simple `button` elements and organizes the code by moving the `PopoverContent` component inside the `Popover` component. These changes simplify the code structure and resolve the scrolling issue reported in the issue description.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1696

## Mobile & Desktop Screenshots/Recordings

Before:

https://github.com/open-sauced/app/assets/106407013/7deaeb7b-258b-44a4-9eec-b2d4628ca820

After:

https://github.com/open-sauced/app/assets/106407013/7b1fe39b-8b72-4951-8c82-2b9da7c86f63

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-09-18 13:22 UTC, OgDev-01 commented
Hey @RitaDee, Thanks for pushing this fix 🍕. Will you take a look at updating the styles of the popover content to match what we have with the dropdown?.

### Expected look
![Screenshot 2023-09-18 at 14 19 37](https://github.com/open-sauced/app/assets/62995161/22d4e20a-f354-4108-81fd-d0fc43e39c2b)

### How it looks now
![Screenshot 2023-09-18 at 14 20 56](https://github.com/open-sauced/app/assets/62995161/4271245b-69cc-4407-8be5-b532f8ddf50f)

The width and padding needs a bit of adjustment

2023-09-18 18:39 UTC, RitaDee commented
> Hey @RitaDee, Thanks for pushing this fix 🍕. Will you take a look at updating the styles of the popover content to match what we have with the dropdown?.
> 
> ### Expected look
> ![Screenshot 2023-09-18 at 14 19 37](https://user-images.githubusercontent.com/62995161/268656776-22d4e20a-f354-4108-81fd-d0fc43e39c2b.png)
> 
> ### How it looks now
> ![Screenshot 2023-09-18 at 14 20 56](https://user-images.githubusercontent.com/62995161/268657056-4271245b-69cc-4407-8be5-b532f8ddf50f.png)
> 
> The width and padding needs a bit of adjustment

Sure!

2023-09-18 21:44 UTC, jpmcb requested changes
A few things have regressed in this PR:
- The default state of the button should be "Following". Hovering over "Following" should dynamically swap the button over to "Unfollow"
- Hovering over either of the options should highlight it with the orange color
- Sizing of the popover has changed and still isn't quite right

Currently on production:
![Screenshot 2023-09-18 at 3 40 24 PM](https://github.com/open-sauced/app/assets/23109390/5a6143c0-7d34-4549-aa99-c5bed642b973)

Proposed change:
![Screenshot 2023-09-18 at 3 42 59 PM](https://github.com/open-sauced/app/assets/23109390/9af7edf0-d529-405b-8c56-09252c0d90bd)

2023-09-19 04:47 UTC, NsdHSO commented
@RitaDee IMHO in my daily dev  this feature is a little bit annoying because if you scroll the tooltip is above the toolbar, and it is a little bit confusing

2023-09-19 13:07 UTC, RitaDee commented
> @RitaDee IMHO in my daily dev this feature is a little bit annoying because if you scroll the tooltip is above the toolbar, and it is a little bit confusing

I have worked on the positioning. That was the fix.

2023-09-19 16:03 UTC, ThePiyushAggarwal commented
Some issues that are happening with this change as well.

https://github.com/open-sauced/app/pull/1712#issuecomment-1725812447
https://github.com/open-sauced/app/pull/1712#issuecomment-1725923347

2023-09-19 17:48 UTC, OgDev-01 requested changes
We are almost there. Just a few tweaks and this is good to go 👍

2023-09-19 17:48 UTC, OgDev-01 commented on components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
> +                        className="rounded-md flex gap-1 !cursor-pointer hover:text-sauced-orange hover:bg-orange-100 [&>span>span:nth-child(1)]:hover:hidden [&>span>span:nth-child(1)]:focus:hidden [
having this odd behavior when i try to hover by the end right character 
![Screenshot 2023-09-19 at 18 39 00](https://github.com/open-sauced/app/assets/62995161/c2e57d1c-e917-43ef-a9b9-ad21efe5ca98)
```suggestion
                        className="rounded-md flex gap-1 !cursor-pointer hover:text-sauced-orange hover:bg-orange-100"
```
Those pseudo-classes are not needed anymore.

2023-09-19 17:48 UTC, OgDev-01 commented on components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
> +                            <div className="group relative">
```suggestion
                            <>
```
Keep this as a fragment so the hover effect works on not just the text but the fill width of the button

https://github.com/open-sauced/app/assets/62995161/1c1d8378-4819-48dc-be20-dade8874aea8

2023-09-19 17:48 UTC, OgDev-01 commented on components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
>                          <span className="pl-3 pr-7">
Move the `group` classname to this span and also make it span the full with of the button.

2023-09-19 18:52 UTC, ThePiyushAggarwal commented
Please check this out. https://github.com/open-sauced/app/pull/1712#issuecomment-1726300898

2023-09-19 21:01 UTC, RitaDee commented
> Please check this out. [#1712 (comment)](https://github.com/open-sauced/app/pull/1712#issuecomment-1726300898)

Thank you @ThePiyushAggarwal. I have done the fix.

2023-09-19 23:14 UTC, jpmcb approved these changes
Great work on this!!!!! And shoutout to @ThePiyushAggarwal for the great investigation / deep dive on this too 🚀 🍕

2023-09-20 14:02 UTC, brandonroberts approved these changes

2023-09-20 14:02 UTC, merged