Feat#1462 show onboarding btn on small screens
open-sauced/app pull request #1803
Opened 2023-10-04 21:54 UTC by 289Volts

## Show onboarding button on small screens

This PR adds the onboarding button on mobile screens up to 640px breakpoint

## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes #1462

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/66239216/6a6f23e2-f62a-47e4-b120-9f44e38f5569

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-10-04 22:14 UTC, OgDev-01 commented
Hey @289Volts , thanks for opening a PR for this fix 👏👏... i think you have a merge conflict to resolve 👍

2023-10-05 22:44 UTC, 289Volts commented
> Hey @289Volts , thanks for opening a PR for this fix 👏👏... i think you have a merge conflict to resolve 👍

Thank you for your feedback. I have resolved the merge conflicts and i await your honest review on the PR

2023-10-06 09:40 UTC, OgDev-01 commented
Try running the build locally to fix the build error @289Volts

2023-10-07 03:17 UTC, babblebey commented
Hey @289Volts 

From your screencast demoing the implementation, the Onboarding button seem to not be displayed at all on Desktop/Larger screen sizes.

We wish for the button to display on these screen size too.

2023-10-07 03:18 UTC, babblebey reviewed
Hey @289Volts 

From your screencast demoing the implementation, the Onboarding button seem to not be displayed at all on Desktop/Larger screen sizes.

We wish for the button to display on these screen size too.

2023-10-09 16:53 UTC, 289Volts commented
> Hey @289Volts
> 
> From your screencast demoing the implementation, the Onboarding button seem to not be displayed at all on Desktop/Larger screen sizes.
> 
> We wish for the button to display on these screen size too.

The reason for this is because the onboarding component is in two different sections of the header. the one that is shown on mobile is intentional to display the fix for this issue

2023-10-09 20:26 UTC, 289Volts commented
I have also discovered that on large screens (1024px), the onboarding button text wraps to the second line because of lack of space to accommodate all the elements in the header.

![localhost_3001_hub_insights](https://github.com/open-sauced/app/assets/66239216/498b188a-ec55-4db8-ad51-6f85617e1bf8)

 The fix i propose is to use the same toolpicker style used for mobile screens for large screens too

![localhost_3001_hub_insights (1)](https://github.com/open-sauced/app/assets/66239216/35b99902-81c5-4d9d-ba36-e99bbb307c75)

OR show the tool tip when they hover on the button icon (it is accessible to screen readers)

https://github.com/open-sauced/app/assets/66239216/9ce2140d-3a25-460a-9883-031be5f5d877

2023-10-09 21:14 UTC, 289Volts commented
> Try running the build locally to fix the build error @289Volts

I have run the build and i discovered the error wasn't caused by a component i worked on. 

![Screenshot (43)](https://github.com/open-sauced/app/assets/66239216/e794fb6b-784a-4151-8d1f-28a797e9cdf3)

2023-10-10 05:47 UTC, OgDev-01 commented
From the above screenshot, it seems you don't have the `@nivo/bar` package installed. crosscheck to confirm you have 
![image](https://github.com/open-sauced/app/assets/62995161/92a2eee8-3809-4404-b37d-2fafe4b3b62b)
in the `package.json` file. if no, then try installing it with `npm i @nivo/bar` else, just run `npm ci` to update your dependencies

2023-10-12 13:53 UTC, OgDev-01 approved these changes
This workd 🍕

2023-10-12 13:59 UTC, brandonroberts requested changes

2023-10-12 13:59 UTC, brandonroberts commented on .eslintrc.json
> +    ],
```suggestion
    "prettier/prettier": ["error",{"endOfLine": "auto"}],
```

2023-10-12 13:59 UTC, brandonroberts commented on components/molecules/AuthSection/auth-section.tsx
> +  console.log(user, onboarded);
```suggestion
```

2023-10-12 13:59 UTC, brandonroberts commented on components/molecules/AuthSection/auth-section.tsx
> +                    {/* <OnboardingButton aria="onboarding" className="!flex !pr-1">
Delete unused code

2023-10-12 13:59 UTC, brandonroberts commented on components/molecules/AuthSection/auth-section.tsx
> +                // <>
Delete unused code

2023-10-12 13:59 UTC, brandonroberts commented on components/molecules/OnboardingButton/onboarding-button.tsx
> +      {children && children}
Why not just `children`?

2023-10-16 13:58 UTC, brandonroberts approved these changes

2023-10-16 13:58 UTC, merged