fixed #1790 create highlight view not responsive to small or large sc…
open-sauced/app pull request #1844
Opened 2023-10-10 09:36 UTC by ryuk-jayant

…reens.

## Description
fixed the #1790 and made highlight view responsive.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ✅ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ✅ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

for mobile screens:
![image](https://github.com/open-sauced/app/assets/97748684/e3736a8f-d975-4a81-911f-dde455f8aa30)

for large screens:
![image](https://github.com/open-sauced/app/assets/97748684/edaa864b-0cde-4832-bf5f-0c4b6a3bc5a7)

## Added tests?

- [ ] 👍 yes
- [ ✅ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ✅ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-10-12 13:35 UTC, OgDev-01 requested changes

2023-10-12 17:16 UTC, ryuk-jayant commented on components/molecules/HighlightInput/highlight-input-form.tsx
> +          // style={{}}
removed dead code

2023-10-13 14:49 UTC, takanome-dev reviewed
Hey @ryuk-jayant, I tested this on Chrome and Firefox and it seems like it's still not responsive on small screens

![2023-10-13_14-47](https://github.com/open-sauced/app/assets/79809121/f69e329a-8b85-4c17-b788-c8d91d7da668)

2023-11-07 15:04 UTC, brandonroberts commented
Closing this for now. Please reopen or open a new PR when ready to pick it back up

2023-11-07 15:04 UTC, closed without merging