fix: popover display issue of safari
open-sauced/app pull request #1962
Opened 2023-10-20 13:16 UTC by OgDev-01

## Description
This PR is a hacky fix to the radix popover and dialog issue in safari

### What i did
- refactored the popover to use a predefined `useState` to handle the open and close state manually
- set the open state to `true` on icon click
- add an mouse event listener to the document to know detect when a user clicks outside the popover content so i can set the open state to `false`.
- also added an addition `useEffect` to set the open state to `false` when users select a date( can be reverted if it is not necessary)

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
fixes #1144

## Mobile & Desktop Screenshots/Recordings
### Before

https://github.com/open-sauced/app/assets/62995161/cb11c435-9bf8-4e61-860b-910c8535f882

### After
https://github.com/open-sauced/app/assets/62995161/ea14a093-a818-4da5-9bff-796b8e6ff265

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

<img src="https://media3.giphy.com/media/3Os1TGIeBzkSlI5lDK/giphy-downsized-medium.gif"/>

2023-10-20 13:49 UTC, OgDev-01 commented
Just remembered we have this also in the create highlight form... adding this fix there shortly

2023-10-20 15:12 UTC, OgDev-01 commented
This is good for review now @open-sauced/engineering

2023-10-20 15:23 UTC, brandonroberts approved these changes

2023-10-20 15:23 UTC, brandonroberts commented on components/molecules/HighlightInput/highlight-input-form.tsx
> +                          console.log("::::: ", createPopoverOpen);
nit: remove console.log
```suggestion
```

2023-10-20 15:35 UTC, OgDev-01 commented on components/molecules/ContributorHighlight/contributor-highlight-card.tsx
> +  useEffect(() => {
Thanks! 🙏 . done

2023-10-20 18:32 UTC, nickytonline commented on components/molecules/ContributorHighlight/contributor-highlight-card.tsx
> +  useEffect(() => {
Going to take it for a test drive

2023-10-20 18:44 UTC, nickytonline requested changes

2023-10-20 18:44 UTC, nickytonline commented on components/molecules/HighlightInput/highlight-input-form.tsx
> +        setDialogOpen(false);
These changes are good like we discussed in our pairing session yesterday, but they are not related to the fix.

Create a separate PR for moving `setIsDivFocused` -> `setDialogOpen` and `isDivFocused` -> `dialogOpen`.

2023-10-20 18:56 UTC, nickytonline reviewed
Once the unrelated refactor changes are reverted, this is good to go.

We should look into encapsulating the fix you made here into a component so that we can reuse this elsewhere if we need a `<Popover />` again in a dialog, but let's wait until that happens.

2023-10-23 14:58 UTC, nickytonline requested changes

2023-10-23 14:58 UTC, nickytonline commented on components/molecules/HighlightInput/highlight-input-form.tsx
> +                      <div
refactor (blocking): this needs to stay as a button so that it can receive focus.

2023-10-23 15:01 UTC, jpmcb approved these changes
From a QA perspective, looks good on Safari!

2023-10-23 15:45 UTC, nickytonline approved these changes
Thanks for making the changes @OgDev-01!

:shipit:

2023-10-23 15:45 UTC, nickytonline approved these changes
Thanks for making the changes @OgDev-01!

:shipit:

2023-10-23 15:58 UTC, merged