feat: updating last contributed column for insights table
open-sauced/app pull request #2115
Opened 2023-11-11 07:35 UTC by jdwilkin4

## Description

This PR is responsible for moving the last contributed repo from under the contributor name to underneath the last contributed column in the insights table. 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
closes #2110 

## Mobile & Desktop Screenshots/Recordings

### Mobile(Before)
<img width="459" alt="Screenshot 2023-11-10 at 11 33 47 PM" src="https://github.com/open-sauced/app/assets/67210629/b485b7f7-3bc6-4b37-a17c-989777ddb057">

### Mobile(After)
<img width="474" alt="Screenshot 2023-11-10 at 11 34 02 PM" src="https://github.com/open-sauced/app/assets/67210629/84391141-d674-47dd-9c95-df2328b8700e">

### Desktop(Before)

<img width="729" alt="Screenshot 2023-11-10 at 11 34 37 PM" src="https://github.com/open-sauced/app/assets/67210629/00f4dfa7-1e00-46df-9235-a498369bfa31">

### Desktop(After)

<img width="736" alt="Screenshot 2023-11-10 at 11 34 48 PM" src="https://github.com/open-sauced/app/assets/67210629/de60ce8d-f3b3-4309-82ee-c96474c2daa4">

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-11-13 16:36 UTC, OgDev-01 approved these changes
Aside the comment i left, this all looks good 👏👏👏. Thanks for taking this on @jdwilkin4

2023-11-13 16:36 UTC, OgDev-01 commented on components/molecules/ContributorListTableRow/contributor-list-table-row.tsx
> +              {truncateString(user?.company || getLastContributedRepo(data), 20)}
We are incrementally moving out of this approach in truncating string, you should look at https://github.com/open-sauced/app/issues/1763 for the new approach 👍

2023-11-13 20:27 UTC, nickytonline requested changes

2023-11-13 20:27 UTC, nickytonline commented on components/molecules/ContributorListTableRow/contributor-list-table-row.tsx
> +                className="text-sm font-normal truncate whitespace-nowrap overflow-hidden overflow-ellipsis text-light-slate-9 md:hidden"
This works, but the columns are getting too large in some cases due to a long org/project name and the ellipsis isn't kicking in, e.g.

![CleanShot 2023-11-13 at 15 15 03](https://github.com/open-sauced/app/assets/833231/a3047c20-7f17-4574-b513-eb4af031b5d5)

A max width would help with this.

I think longer term we need to revisit this grid, but for now, that should help with the misalignment.

2023-11-15 07:40 UTC, NsdHSO commented on components/molecules/ContributorListTableRow/contributor-list-table-row.tsx
> +                className="text-sm font-normal truncate whitespace-nowrap overflow-hidden overflow-ellipsis text-light-slate-9 md:hidden lg:max-w-[130px]"
instead `130px` why not `8.12rem`?

2023-11-15 14:14 UTC, OgDev-01 requested changes

2023-11-15 14:14 UTC, OgDev-01 commented on components/molecules/ContributorListTableRow/contributor-list-table-row.tsx
> +                className="text-sm font-normal truncate whitespace-nowrap overflow-hidden overflow-ellipsis text-light-slate-9 md:hidden lg:max-w-[8.12rem]"
truncate in tailwind is a combination of 
- overflow-hidden
- text-overflow-ellipsis
- whitespace-nowrap

all you need to achieve the truncate here is the `truncate` class

```suggestion
                className="text-sm font-normal truncate text-light-slate-9 md:hidden lg:max-w-[8.12rem]"
```

2023-11-15 16:17 UTC, OgDev-01 approved these changes
All good now 🍕🍕

2023-11-15 20:38 UTC, brandonroberts approved these changes

2023-11-15 20:39 UTC, merged

2023-11-15 20:39 UTC, brandonroberts commented
Thanks @jdwilkin4!