Svelte added to interests dropdown list
open-sauced/app pull request #2168
Opened 2023-11-17 15:01 UTC by brittneypostma

## Description

added svelte to interests dropdown list

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2167

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-11-17 16:18 UTC, nickytonline requested changes
Thanks for the pull request @brittneypostma!

It looks like we need to add some info in regards to Svelte elsewhere as well. We need an icon
for it in SVG format. See this file, https://github.com/open-sauced/app/blob/beta/lib/utils/getTopicThumbnail.ts, to add it and for examples for other languages.

2023-11-19 21:16 UTC, brittneypostma commented
Thanks Nick, just added the logo, not sure what else you need for it. Just let me know :)

2023-11-19 21:52 UTC, nickytonline commented
Looks like it works but there are some type errors failing the build.

4:49:27 PM: ./lib/utils/recommendations.ts:3:7
4:49:27 PM: Type error: Property "svelte" is missing in type "{ react: string[]; javascript:
stringIl; python: string|]; ml: string|]; ai: stringI]; rust: string[l; ruby: string[]; c:
stringIl; cpp: string|]; csharp: string|]; php: string|]; java: string[]; typescript: string|];
golang: string||; vue: string||; kubernetes: string|]; hacktoberfest: string|]; clojure:
stringIl; }" but required in type "Record<"ruby" | "javascript" | "python" | "java" ||
"typescript" | "csharp" | "cpp" | "php" | "c" | "ai" | "ml" | "react" | "golang" | "rust" |
"svelte" | "vue" | "kubernetes" | "hacktoberfest" | "clojure", string[]>".
4:49:27 PM: 1 | import { interestsType } from "./getInterestOptions";
4:49:27 PM: 2
4:49:27 PM: > 3 | const recommendations: Record‹interestsType, string[]> = {
4:49:27 PM: ^
4:49:27 PM: 4 | react: ["Skyscanner/backpack"],
4:49:27 PM: 5 | javascript: ["EddieHubCommunity/LinkFree"],
4:49:27 PM: python: ["randovania/randovania"],
4:49:28 PM: Failed during stage "building site": Build script returned non-zero exit code: 2

2023-11-20 11:20 UTC, nickytonline commented
Looks like there’s another compile error. 

```
6:14:54 AM: Failed during stage "building site": Build script returned non-zero exit code: 2
6:14:54 AM: Failed to compile.
6:14:54 AM: 
6:14:54 AM: ./lib/utils/recommendations.ts:3:7
6:14:54 AM: Type error: Property "svelte" is missing in type "{ react: string[]; javascript: string[]; python: string[]; ml: string[]; ai: string[]; rust: string[]; ruby: string[]; c: string[]; cpp: string[]; csharp: string[]; php: string[]; java: string[]; typescript: string[]; golang: string[]; vue: string[]; kubernetes: string[]; hacktoberfest: string[]; clojure: string[]; }" but required in type "Record<"ruby" | "javascript" | "python" | "java" | "typescript" | "csharp" | "cpp" | "php" | "c" | "ai" | "ml" | "react" | "golang" | "rust" | "svelte" | "vue" | "kubernetes" | "hacktoberfest" | "clojure", string[]>".
```

Once that error is sorted, run `npm run build` to see if there are any other TypeScript compilation errors.

2023-11-20 11:52 UTC, brittneypostma commented
Yeah, trying to do this in GitPod and not getting much feedback. I'm surprised it's passing the commit lint, but I guess if I'm not touching the file, it doesn't see it. I'm not sure what this file is asking for on the value props here. 
![image](https://github.com/open-sauced/app/assets/45889730/1dfcb469-5176-45d2-9472-6e7ff2ca0d21)

2023-11-20 13:03 UTC, nickytonline commented
I can take a peek. I'll see what's missing. I'll be live streaming code reviews in an hour as that's how I usually start my Mondays, so we can see what's up.

2023-11-20 14:28 UTC, nickytonline approved these changes
This is all working now @brittneypostma. Thanks for the PR!

2023-11-20 14:28 UTC, nickytonline commented on lib/utils/recommendations.ts
> +  svelte: ["sveltejs/svelte"],
I pushes this change @brittneypostma to fix the build error.

2023-11-20 15:09 UTC, brandonroberts approved these changes
🚀

2023-11-20 15:53 UTC, merged