fix: Dashboard Highlight card skeleton covers hovercard details
open-sauced/app pull request #2237
Opened 2023-11-30 04:18 UTC by Anish0203

## Description

This PR fixes the following bug: 
When the stats are still loading on the page https://app.opensauced.pizza/javascript/dashboard/filter/recent?range=30, hovering on a contributor from the repositories table would lead to hovercard details being covered by the dashboard highlight card skeleton.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2193 

## Mobile & Desktop Screenshots/Recordings

Before:
![before_hovercard](https://github.com/open-sauced/app/assets/45678877/7d4e6382-10ae-40b5-8b5d-dd6af57c0b39)

After:
![after_hovercard](https://github.com/open-sauced/app/assets/45678877/74dafb76-4828-428c-8d27-fee7c939b2d3)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-11-30 15:39 UTC, nickytonline requested changes
Thanks for the PR @Anish0203! There's actually no need to add any z-indexes.

We actually need to remove z-indexes. 😎

The only change that needs to be done is in the globals.css file.

We need to remove the z-index from the react-skeleton class which is the CSS class used by the <Skeleton /> component.

```diff
@tailwind base;
@tailwind components;
@tailwind utilities;

@font-face {
  font-family: "Inter";
  font-display: fallback;
  src: url("../public/assets/fonts/Inter-VariableFont_slnt,wght.ttf");
}

body {
  @apply font-normal;
  background-color: #f8f9fa;
}

h1,
h2,
h3,
h4,
h5,
h6 {
  @apply tracking-tight;
}

input[type="checkbox"]:focus-visible,
[role="checkbox"]:focus-visible {
  @apply outline-none;
  @apply ring;
  @apply border-orange-500;
  @apply ring-orange-100;
}

/* See https://github.com/open-sauced/app/issues/2210 */
[role="checkbox"] > [data-state="checked"] > svg {
  stroke-width: 5;
}

.auto-grow-input:not(:empty) {
  color: black;
}
.auto-grow-input[contenteditable]:empty::before {
  content: "List Name";
  color: "#d1d5db" !important;
}

.login-step .sbui-btn-container {
  width: 100%;
}

.border-conic-gradient {
  background-image: conic-gradient(
    from 180deg at 50% 50%,
    #ff6a06 0deg,
    #ff6492 120.00000357627869deg,
    #ffe22c 223.12500715255737deg,
    #fc620d 360deg,
    #ff7e33 360deg
  );
}

.sbui-btn > span {
  display: flex;
  align-items: center;
}

.sbui-select:focus-visible {
  border: 1px solid #f76808 !important  ;
  box-shadow:
    0px 0px 0px 2px #ffcca7,
    0px 1px 2px rgba(0, 0, 0, 0.1) !important;
}

.sbui-checkbox:hover {
  border-color: #f76808 !important;
}

input[type="search"]::-webkit-search-cancel-button {
  -webkit-appearance: none !important;
}

.z-10 {
  z-index: 10;
}

.z-20 {
  z-index: 20;
}

.z-30 {
  z-index: 30;
}

.z-40 {
  z-index: 40;
}

.z-50 {
  z-index: 50;
}

div[role="dialog"]::-webkit-scrollbar {
  width: 16px;
  height: 10px;
}
div[role="dialog"]::-webkit-scrollbar-thumb {
  border: 4px solid rgba(0, 0, 0, 0);
  border-radius: 8px;
  background: #c2c9d2;
  background-clip: padding-box;
}
.swiper {
  padding-bottom: 25px !important;
}
:root {
  --swiper-theme-color: hsla(19, 100%, 50%, 1) !important;
  --swiper-pagination-bottom: -5px;
  --swiper-pagination-bullet-inactive-color: rgb(255, 159, 115);
  --swiper-pagination-bullet-size: 8px;
}

.newsletter-wrap {
  container: newsletterWrap / inline-size;
}

@container newsletterWrap (max-width: 240px) {
  .form-wrap {
    flex-wrap: wrap;
  }
  .form-wrap button {
    width: 100%;
  }
}

.loading {
  animation-duration: 1.25s;
  animation-fill-mode: forwards;
  animation-iteration-count: infinite;
  animation-name: placeHolderShimmer;
  animation-timing-function: linear;
  background: linear-gradient(
    to right,
    rgba(255, 255, 255, 0.1) 10%,
    rgba(0, 0, 0, 0.05) 25%,
    rgba(255, 255, 255, 0.1) 40%
  );
  box-shadow: inset 0 0 0 200px rgba(0, 0, 0, 0.05);
  background-size: 800px 104px;
  position: relative;
}

.radix-select-trigger span {
  flex: 1;
  text-align: left;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

@keyframes placeHolderShimmer {
  0% {
    background-position: -468px 0;
  }
  100% {
    background-position: 468px 0;
  }
}
+ 
+ .react-loading-skeleton {
+   z-index: unset !important;
+ }
+ 
```

2023-12-02 11:38 UTC, Anish0203 commented
Thanks @nickytonline for letting me know the changes.

2023-12-02 12:42 UTC, nickytonline approved these changes
Thanks for the fix @Anish0203! 🚀

2023-12-06 20:06 UTC, brandonroberts approved these changes

2023-12-06 20:06 UTC, merged