fix: issue #2328 Select All doesn't clear when moving to the next pag…
open-sauced/app pull request #2341
Opened 2023-12-15 14:41 UTC by aryanas159

…e of contributors

## Description
fixes #2328 
I have added a state to check whether the checkbox for 'select all' is checked or not and added the required logic to add users across multiple pages, the same issue was with the add contributors to list page as well as the new list creating page. I have fixed those as well.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/114330931/086a84e9-9419-4b81-9061-ac628a07ea11

## Steps to QA

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?
![FinallyFinishedGIF (2)](https://github.com/open-sauced/app/assets/114330931/fdc2322b-1703-4a20-88b7-89bd7d2d865b)

2023-12-21 09:26 UTC, OgDev-01 commented
Thanks for this fix @aryanas159 🍕. Can you also apply the same fix to the repositories table if you have the bandwidth?

2023-12-21 09:31 UTC, aryanas159 commented
> Thanks for this fix @aryanas159 🍕. Can you also apply the same fix to the repositories table if you have the bandwidth?

Sure, I can look into it.

2023-12-21 17:35 UTC, aryanas159 commented
@OgDev-01 I have made the changes for the repository table.

2023-12-22 17:05 UTC, OgDev-01 commented
> @OgDev-01 I have made the changes for the repository table.

Thanks for tackling this @aryanas159... I'll take a peak on this shortly 👍

2023-12-22 17:40 UTC, OgDev-01 approved these changes
LGTM... Well done 👏 👏  @aryanas159

2023-12-22 20:15 UTC, jpmcb reviewed
Looks good! Approved the build preview and went through it: looks good! I'll leave it to others for code / style review. But LGTM

2024-01-04 23:32 UTC, nickytonline commented on components/organisms/Contributors/contributors.tsx
> +  useEffect(() => {
Any reason this requires a `useEffect`? This should be driven by the check/uncheck in the `onClick` even if the paged data changes.

2024-01-04 23:34 UTC, nickytonline requested changes
Any reason this requires a `useEffect`? This should be driven by the check/uncheck in the `onClick` even if the paged data changes.

Instead, when the new page of data loads, the event that changes the page should call `setIsSelectAll(false)`.

2024-01-05 04:29 UTC, aryanas159 commented
@nickytonline If we call ```setIsSelectAll(false)``` every time the page changes, those elements will also be removed if we move to a page where we have selected all previously. Also the ```useEffect``` ensures that if a user manually selects all the users on a page, then the ```select all``` checkbox will also be checked.

2024-01-06 20:31 UTC, nickytonline commented
> @nickytonline If we call `setIsSelectAll(false)` every time the page changes, those elements will also be removed if we move to a page where we have selected all previously. Also the `useEffect` ensures that if a user manually selects all the users on a page, then the `select all` checkbox will also be checked.

This is true; however, that is some select all functionality that all our grids are missing. Currently, if you select all, it's for the current page only, but when we do that, we probably want to give an option like in GMail to select all the data.

![CleanShot 2024-01-06 at 15 30 18](https://github.com/open-sauced/app/assets/833231/00fdc158-d619-4ec8-a1f8-b6d5faabe76e)

2024-01-16 17:31 UTC, brandonroberts commented
I agree with @nickytonline. I think we need some more thought on this and should close this for now.

2024-01-16 17:51 UTC, closed without merging

2024-01-16 17:52 UTC, nickytonline commented
Thanks for working on this @aryanas159. Once we get the true  select all in place, we can revisit this.