refactor: add page and limit to urlParams
open-sauced/app pull request #2526
Opened 2024-01-25 12:00 UTC by OgDev-01

## Description
This PR is still a WIP

### TODO

- [ ] Add page and limit query to insights and list index page
- [ ] Add page query to insights pages
- [ ] add page query to explore page

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Steps to QA

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-01-26 05:48 UTC, OgDev-01 commented
We have a duplicate story with same id that breaks this build
![image](https://github.com/open-sauced/app/assets/62995161/6982a274-f4e9-4824-a167-4f2cd5caa864)

One in the molecules dir and the other in graphs
https://github.com/OgDev-01/app-opensauced/blob/39442930dcc13773cd9e3fb5702060c25816c823/components/Graphs/ContributionsTreemap/contributions-treemap.stories.tsx and https://github.com/OgDev-01/app-opensauced/blob/f8092ee9cb9dde84cddc1c340e63fc7f2365a9f1/components/molecules/ContributionsTreemap/contributions-treemap.stories.tsx

The story mockup seems different, and I'm wondering if these two stories need to co-exist. If that is the case, we need to update the naming to be unique to avoid duplicate id's. cc: @nickytonline

2024-01-30 15:01 UTC, brandonroberts commented
@OgDev-01 the ContributionsTreemap under `components/molecules` is gone, so there should only be one. We landed the API v2 change on beta and cleaned that up

2024-02-05 20:29 UTC, brandonroberts commented
@OgDev-01 will you add a screen capture demo of the feature and fix the merge conflicts?

2024-02-05 22:20 UTC, nickytonline commented
> We have a duplicate story with same id that breaks this build ![image](https://private-user-images.githubusercontent.com/62995161/299888900-6982a274-f4e9-4824-a167-4f2cd5caa864.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNzE4MzYsIm5iZiI6MTcwNzE3MTUzNiwicGF0aCI6Ii82Mjk5NTE2MS8yOTk4ODg5MDAtNjk4MmEyNzQtZjRlOS00ODI0LWExNjctNGYyY2Q1Y2FhODY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDIyMTg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMjQxNGFiZDI5MzNhNjJjYzhjZWNmNDA0ZGMxNzUxZmUzOTcyYzc2OWZlMDU3ZDZiNjEyM2I4MDNkMmU1MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qn1YStGisBTEJ53uBCdDWKQL3rWIEakvbZ9EtTgS1tE)
> 
> One in the molecules dir and the other in graphs [OgDev-01/app-opensauced@`3944293`/components/Graphs/ContributionsTreemap/contributions-treemap.stories.tsx](https://github.com/OgDev-01/app-opensauced/blob/39442930dcc13773cd9e3fb5702060c25816c823/components/Graphs/ContributionsTreemap/contributions-treemap.stories.tsx) and [OgDev-01/app-opensauced@`f8092ee`/components/molecules/ContributionsTreemap/contributions-treemap.stories.tsx](https://github.com/OgDev-01/app-opensauced/blob/f8092ee9cb9dde84cddc1c340e63fc7f2365a9f1/components/molecules/ContributionsTreemap/contributions-treemap.stories.tsx)
> 
> The story mockup seems different, and I'm wondering if these two stories need to co-exist. If that is the case, we need to update the naming to be unique to avoid duplicate id's. cc: @nickytonline

You'll need to get latest as there are no duplicate stories. It got moved in a PR a while back. You can see in beta.

2024-02-06 16:06 UTC, OgDev-01 commented
> @OgDev-01 will you add a screen capture demo of the feature and fix the merge conflicts?

On it now..

2024-02-07 15:09 UTC, nickytonline requested changes
I'm hesitant to merge all these changes all at once. Can we break this PR into several so that we can do it either a couple pages at a time  or per hook?

2024-02-07 15:09 UTC, nickytonline commented on components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
> +  const { data } = useFetchAllLists({});
refactor (blocking): passing an empty object doesn't make sense, it all the properies are optional, you can default to an empty object in the hook.

2024-02-09 05:26 UTC, OgDev-01 commented
> I'm hesitant to merge all these changes all at once. Can we break this PR into several so that we can do it either a couple pages at a time or per hook?

Alright @nickytonline, I'll be breaking this into smaller pieces in several PRs during the weekend, if that is okay by you?

2024-03-27 15:44 UTC, closed without merging