feat: track contributors in workspaces
open-sauced/app pull request #2629
Opened 2024-02-09 09:58 UTC by zeucapua

## Description

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Steps to QA

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-02-13 23:15 UTC, zeucapua commented
Redeploying on Netlify completes the build fine, I don't know how to re-run the deploy via Github to clear the Netlify checks.

2024-02-14 20:45 UTC, bdougie approved these changes
I did a bit of QA on this and LGTM

2024-02-14 20:45 UTC, isabensusan approved these changes
working great for me!

2024-02-14 21:01 UTC, nickytonline requested changes
This is working great @zeucapua. A few change requests.

2024-02-14 21:14 UTC, jpmcb approved these changes

2024-02-14 21:14 UTC, jpmcb commented on lib/utils/workspace-utils.ts
> +  });
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbGJ5bHE0MXI5eWd2dDYzMHZnNWUzMWZxejdxZDNycnE4ZWM5ZDhtZSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l3vRjZN3rXQBWYjBu/giphy.gif)

2024-02-14 21:37 UTC, zeucapua commented on lib/utils/workspace-utils.ts
> +  });
🫡

2024-02-14 21:39 UTC, nickytonline approved these changes
<img src="https://media0.giphy.com/media/jCbI7v2NHaLrJF4le4/giphy.gif"/>

2024-02-14 21:51 UTC, merged