feat: add upgrade section in workspace settings
open-sauced/app pull request #2726
Opened 2024-02-20 21:45 UTC by zeucapua

## Description

Implementing a section that will allow users to upgrade the workspace.
- [x] Add designed section
- [ ] Hide if workspace is already upgraded
- [ ] Go to Stripe checkout on click

## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Steps to QA

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![upgrade-you-beyonce-gif](https://github.com/open-sauced/app/assets/20603494/e81c6e11-acb2-41ce-b6ac-d7a8adaf30c7)

2024-02-21 15:22 UTC, isabensusan commented
this is looking great!!

I know this is only a draft, but just in case, here's a couple notes on styling

Font fixes:
<img width="1357" alt="image" src="https://github.com/open-sauced/app/assets/27322879/6c2b9519-bb46-4cfd-b12a-3c873fedf510">

Padding fixes:
<img width="1355" alt="image" src="https://github.com/open-sauced/app/assets/27322879/6d1b4587-6df5-40f3-bdfb-a98658e94349">

thank youuuu

2024-02-22 14:54 UTC, jpmcb commented on lib/utils/workspace-utils.ts
> +    body: {},
If this isn't getting added automatically by the empty post request, a header here for `Content-Length: 0` would be ideal

2024-02-22 16:41 UTC, isabensusan commented
Thought you might need this too -- once the workspace is upgraded we should show a section to let the user cancel  their pro workspace subscription. Quick and dirty sketch:

<img width="441" alt="image" src="https://github.com/open-sauced/app/assets/27322879/c4a8d7d9-0cd6-424b-b5db-96086db2c6e9">


<img width="1038" alt="image" src="https://github.com/open-sauced/app/assets/27322879/637d943d-4139-432b-8fa7-ebd7810200e7">

2024-02-22 18:51 UTC, jpmcb commented
> Is there a cancel subscription endpoint I should be hitting? I assume there must be a Stripe thing in the backend to ensure they don't get recurring charges after cancelling @jpmcb

Yeah, good question: the webhook will indeed handle canceling the subscriptions (so if the customer logs into their stripe portal and manually cancels it, that gets handled by the webhook event from stripe). We could do something similar where we have a cancel button that forwards them to their stripe dashboard via the `NEXT_PUBLIC_STRIPE_SUB_CANCEL_URL` env var like we currently do for "pro" plans:

https://github.com/open-sauced/app/blob/7e7c3be849b02c44987e293c4e9c0a4c26b9f534/components/organisms/UserSettingsPage/user-settings-page.tsx#L471-L479

Testing this out, it indeed takes me to a dashboard where I can cancel the subscription:

![Screenshot 2024-02-22 at 11 49 09 AM](https://github.com/open-sauced/app/assets/23109390/c679178b-2639-476c-bfe0-92a924e93fc4)

I say we do ^ for now since it'll be easy.

But it's not a great user experience since it'd be confusing for anyone paying for multiple workspaces what they're doing: a few questions for @isabensusan - should the OpenSauced platform handle canceling the subscription? Or should we forward them onto stripe? We could add an endpoint in the API and handle it on our side, just depends on how we want to go about it and what the user experience should feel like.

2024-02-22 18:53 UTC, isabensusan commented
@jpmcb for now, I'd leave it on the Stripe side -- but we do need an entry point on the website for users to get to the stripe page and be able to cancel their subscriptions

2024-02-22 19:41 UTC, brandonroberts requested changes

2024-02-22 19:41 UTC, brandonroberts commented on .env
> +NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51H1yp3JnZ7CYWRG2KmQMIE8sizoaSaZ8FxlEsc5uQb81gVswDlWu6FErmcukqc6Hso3mhCWgnLsjWphight4t1Mf00jZZjckyZ
Revert this as the test key is applied when deployed

2024-02-22 19:41 UTC, brandonroberts commented on pages/workspaces/[workspaceId]/settings.tsx
> +import { loadStripe } from "@stripe/stripe-js";
We have a utility already for loading stripe in `lib/utils/stripe-client.ts`

2024-02-22 20:02 UTC, brandonroberts approved these changes
<img src="https://media4.giphy.com/media/2Ga8aj2mbUFK8/giphy.gif"/>

2024-02-22 20:07 UTC, jpmcb approved these changes

2024-02-22 20:13 UTC, merged