fix: redirect /hub/insights/new to login if not authenticated
open-sauced/app pull request #2935
Opened 2024-03-12 21:24 UTC by brandonroberts

## Description

- Redirects `/hub/insights/new` to `/signin` to prompt user to login if not authenticated

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes https://github.com/open-sauced/app/issues/2599

## Mobile & Desktop Screenshots/Recordings

## Steps to QA

1. Navigate to `/hub/insights/new`
2. Note you're redirected to login and are redirected back to the workspace

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

<img src="https://media1.giphy.com/media/YnmEsq9ICSYQ8/giphy.gif"/>

2024-03-12 21:37 UTC, bdougie commented
The auth flow works, but I land on the highlights feed. TBH, the highlights feed is deprioritized and per the .new requirements we need the user to redirect back to `/hub/insights/new` after authenticating.

2024-03-12 21:37 UTC, jpmcb approved these changes

2024-03-13 15:34 UTC, brandonroberts commented
> The auth flow works, but I land on the highlights feed. TBH, the highlights feed is deprioritized and per the .new requirements we need the user to redirect back to `/hub/insights/new` after authenticating.

This is ready to go now and will redirect to the new repository insight page for their personal after being prompted to login.


https://github.com/open-sauced/app/assets/42211/c534c9af-dd20-481e-9ecc-0b33cf79fb3a

2024-03-13 15:55 UTC, nickytonline commented
> > The auth flow works, but I land on the highlights feed. TBH, the highlights feed is deprioritized and per the .new requirements we need the user to redirect back to `/hub/insights/new` after authenticating.
> 
> This is ready to go now and will redirect to the new repository insight page for their personal after being prompted to login.
> 
>  Screen.Recording.2024-03-13.at.10.33.13.AM.mov

Can we redirect server-side instead back to the new insight page, or is there a limitation with how we log in with GH/Supabase? Currently it goes back to the feed and then redirects what appears to be client-side.

2024-03-13 16:05 UTC, bdougie commented
> Can we redirect server-side instead back to the new insight page, or is there a limitation with how we log in with GH/Supabase? Currently it goes back to the feed and then redirects what appears to be client-side.

Was curious why the redirect back to the feed and then to /new. I assume this is why.

2024-03-13 16:39 UTC, brandonroberts commented
> > > The auth flow works, but I land on the highlights feed. TBH, the highlights feed is deprioritized and per the .new requirements we need the user to redirect back to `/hub/insights/new` after authenticating.
> > 
> > 
> > This is ready to go now and will redirect to the new repository insight page for their personal after being prompted to login.
> > Screen.Recording.2024-03-13.at.10.33.13.AM.mov
> 
> Can we redirect server-side instead back to the new insight page, or is there a limitation with how we log in with GH/Supabase? Currently it goes back to the feed and then redirects what appears to be client-side.

Yea, its two-fold from what I came across.

Supabase doesn't provide an API to generate a login URL server-side, and building the URL manually didn't seem like a good option.

Also, requesting the user session immediately after logging doesn't return a valid session in the middleware, so it falls back to the login page in a loop. Letting the request fall back to the client creates the user session and triggers the redirect correctly.

2024-03-13 16:39 UTC, brandonroberts commented
We can navigate back to the `/signin` page and redirect from there if its less jarring

2024-03-13 20:30 UTC, brandonroberts commented
It now redirects back to `/signin` after logging in before going to its destination path.

2024-03-13 21:03 UTC, nickytonline requested changes

2024-03-13 21:03 UTC, nickytonline commented on pages/signin.tsx
> +        router.replace(decodeURIComponent(destination));
refactor (blocking): `router.query` already decodes the querystring values destructured above. Same for the `redirectedFrom` below.

```suggestion
router.replace(destination);
```

2024-03-13 21:13 UTC, bdougie commented
> * /hub/insights/new

I get an infinite redirect now.

![Rewatch GIF Recording - 2024-03-13 at 5 01 21 PM](https://github.com/open-sauced/app/assets/5713670/3ba5925a-b84a-4720-93f3-84779c03dfc7)

2024-03-14 19:50 UTC, brandonroberts commented
Redirect loop issues should be resolved now. Tested on the deploy preview

2024-03-15 15:23 UTC, bdougie commented
I am still redirecting non-stop.

<img width="1813" alt="Screen Shot 2024-03-15 at 11 20 31 AM" src="https://github.com/open-sauced/app/assets/5713670/c15428da-e110-4843-bba4-8d54587d62a2">

2024-03-18 14:47 UTC, bdougie commented
What is we approach this differently and allow users to see the workspace creation without logging in and force a login and they hit create.

2024-03-19 04:18 UTC, brandonroberts commented
> What if we approach this differently and allow users to see the workspace creation without logging in and force a login and they hit create.

That seems reasonable to me. We already have some login there for using `Create New Workspace` from the dropdown

2024-03-27 16:27 UTC, brandonroberts commented
@bdougie This is ready for another review. `/hub/insights/new` now redirects to creating a new workspace without being logged in and keeps the information entered after logging in.

2024-03-27 21:57 UTC, bdougie approved these changes
works as expected.

2024-03-28 13:53 UTC, merged