bug: text area input does not focus when active and add highlight input is always focussed in post a highlight form
open-sauced/app pull request #3008
Opened 2024-03-22 14:03 UTC by FatumaA

## What this PR does?
This PR:
-  adds a focus on hover for the textarea input 
- fixes the permanent error hover in the add a highlight link input

## What type of PR is this?
- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
closes #2715 

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/67555014/c092dc6e-f422-4267-9da9-ee0d8b349bce

## Steps to QA
1. Go to highlights tab
2. Click on the "post a highlight to show your work" input
3. The "post a highlight" form will pop up
4. Notice that the text-area input is now focussed when clicked on while the add a highlight link input is no longer focussed on load and is focussed when clicked or when in error

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

N/A

## [optional] What gif best describes this PR or how it makes you feel?
N/A

2024-03-22 21:28 UTC, nickytonline requested changes

2024-03-22 21:28 UTC, nickytonline commented on components/molecules/HighlightInput/highlight-input-form.tsx
> +                  // className="text-sm shadow-none h-10 flex-none"
refactor (blocking): `errorMsg && "border-red-500` will result in `undefined` for a class name if there is no error message.

```suggestion
                  state={isHighlightURLValid ? "valid" : "invalid"}
                  className={`text-sm shadow-none h-10 flex-none ${errorMsg ? "border-red-500": ""}`}
```

You could also use `clsx` which is already in the project as well.

```suggestion
                  state={isHighlightURLValid ? "valid" : "invalid"}
                  className={clsx("text-sm shadow-none h-10 flex-none", errorMsg ? "border-red-500": "")}
```

2024-03-22 21:28 UTC, nickytonline commented on components/molecules/HighlightInput/highlight-input-form.tsx
> +            <div className="flex flex-col gap-2 p-2 text-sm bg-white border rounded-lg outline-1 focus-within:outline focus-within:outline-orange-500">
Textareas in general need default focus states like some other components, but it's fine to do it on an individual level for the moment.

These are the styles we currently use for focus on other form inputs.

```suggestion
            <div className="flex flex-col gap-2 p-2 text-sm bg-white border rounded-lg focus-within:outline-none focus-within:ring  focus-within:border-orange-500 focus-within:ring-orange-100">
```

2024-03-24 19:25 UTC, FatumaA commented
Hi Nicky,
Thank you for the review, I have made the suggested changes.

2024-03-24 22:23 UTC, nickytonline approved these changes
Thanks @FatumaA!

2024-03-24 22:23 UTC, nickytonline commented on components/molecules/HighlightInput/highlight-input-form.tsx
> +            <div className="flex flex-col gap-2 p-2 text-sm bg-white border rounded-lg focus-within:outline-none focus-within:ring  focus-within:border-orange-500 focus-within:ring-orange-100">
nit: spacing

```suggestion
            <div className="flex flex-col gap-2 p-2 text-sm bg-white border rounded-lg focus-within:outline-none focus-within:ring focus-within:border-orange-500 focus-within:ring-orange-100">
```

2024-03-25 07:35 UTC, FatumaA commented
> Thanks @FatumaA!

Hi Nicky,
Quick question - you mentioned a uniform type of focus for form inputs across the project, but it appears the input to paste the highlight url in this form has different focus styles than what you suggested.

Should I update the input focus to mirror those styles? I think doing so would ensure visual consistency when interacting with the Post-a-highlight form. 

What are your thoughts?

2024-04-02 13:55 UTC, NsdHSO approved these changes
LGTM

2024-04-02 22:13 UTC, bdougie approved these changes

2024-04-03 11:51 UTC, nickytonline commented
There's just a couple conflicts to sort out @FatumaA and then this is ready to go.

![CleanShot 2024-04-03 at 07 50 29](https://github.com/open-sauced/app/assets/833231/b0179e04-4fd6-4f8f-8c77-fd91ec3b9087)

2024-04-06 12:37 UTC, FatumaA commented
> There's just a couple conflicts to sort out @FatumaA and then this is ready to go.
> 
> ![CleanShot 2024-04-03 at 07 50 29](https://private-user-images.githubusercontent.com/833231/319171020-b0179e04-4fd6-4f8f-8c77-fd91ec3b9087.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MDYzNDksIm5iZiI6MTcxMjQwNjA0OSwicGF0aCI6Ii84MzMyMzEvMzE5MTcxMDIwLWIwMTc5ZTA0LTRmZDYtNGY4Zi04Yzc3LWZkOTFlYzNiOTA4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNlQxMjIwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjUzNmM4Y2E0MmYwZWQzNmE5NDY3OTU1ZTAxMzY1NmM3ZTQ0MzEyNWE3ZGUyYzI5ZDMxODk5MDQyNGM3ZWJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gJZI9uXmhjrjl-gyRGEhnpNZ2L1Ha_kuOKQt5QC7iOw)

please see if its ok, I got into some trouble trying to remove beta history

2024-04-06 13:19 UTC, merged