fix: Contributor Insight & Repository Insight uses wrong copy
open-sauced/app pull request #3227
Opened 2024-04-20 16:11 UTC by Lalithkumarponnambalam

## Description

## Related Tickets & Documents

Fixes #3213

## Mobile & Desktop Screenshots/Recordings

![Screenshot from 2024-04-20 21-40-04](https://github.com/open-sauced/app/assets/139358124/4698e4eb-6853-4240-a936-db4d831b7dce)

![Screenshot from 2024-04-20 21-39-31](https://github.com/open-sauced/app/assets/139358124/cb317c76-f0e6-4634-9caf-a01973e19ae7)

## Steps to QA

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [ ] Tier 4

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-04-20 18:11 UTC, BekahHW requested changes
Looking good! Just a couple of minor changes and should be ready to merge.

2024-04-20 18:11 UTC, BekahHW commented on pages/workspaces/[workspaceId]/contributor-insights/[listId]/edit.tsx
>                Delete workspace
This should be "Delete Insight"

2024-04-20 18:11 UTC, BekahHW commented on pages/workspaces/[workspaceId]/repository-insights/[insightId]/edit.tsx
>                Delete insight
Can you capitalize "Insight" here?

2024-05-02 21:20 UTC, nickytonline approved these changes
Thanks @Lalithkumarponnambalam!

:shipit:

2024-05-02 21:27 UTC, merged