feat: layout changes for repo pages
open-sauced/app pull request #3373
Opened 2024-05-13 21:48 UTC by zeucapua

## Description

## Related Tickets & Documents

Closes #3370 

## Mobile & Desktop Screenshots/Recordings

## Steps to QA

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [x] Tier 3
- [ ] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?

2024-05-14 00:02 UTC, bdougie commented
Weirdness on mobile. https://github.com/open-sauced/app/assets/5713670/0bdbddc3-16ae-4bb7-96d4-c38456470224

2024-05-14 15:57 UTC, isabensusan requested changes
Added some comments on sizing :) 

Should end up looking closer to this:
<img width="1413" alt="image" src="https://github.com/open-sauced/app/assets/27322879/9854e419-ef50-4a0e-9523-4b7a9131144c">

2024-05-14 15:57 UTC, isabensusan commented on components/Repositories/LotteryFactorChart.tsx
> +          <tbody className="!text-xs truncate">
let's make this` text-sm` instead

2024-05-14 15:57 UTC, isabensusan commented on components/molecules/DevProfile/dev-profile.tsx
> -        <AvatarHoverCard contributor={username} repositories={[]} size="small" />
make this `base` instead of `small`

2024-05-14 15:57 UTC, isabensusan commented on components/Repositories/LotteryFactorChart.tsx
>                  <td className={`${hovered === name ? "font-semibold" : "font-normal"} border-b-1 py-4 pl-2`}>
can we make this `py-1` ?

2024-05-14 15:57 UTC, isabensusan commented on pages/s/[org]/[repo]/index.tsx
> +                className="lg:col-span-7"
`className="lg:col-span-8"`

2024-05-14 15:57 UTC, isabensusan commented on pages/s/[org]/[repo]/index.tsx
> +                className="lg:col-span-5"
`className="lg:col-span-4"`

2024-05-14 19:47 UTC, isabensusan commented
Last ask -- can we make the explainer tooltip show up on hover instead of on click?

2024-05-14 19:56 UTC, nickytonline requested changes
On the Remix and Kubernetes repo pages, the top left graph doesn't render properly for some reason.

![CleanShot 2024-05-14 at 15 54 54](https://github.com/open-sauced/app/assets/833231/8c0cdece-c471-4863-99e7-aa208846d86a)

![CleanShot 2024-05-14 at 15 56 18](https://github.com/open-sauced/app/assets/833231/91c654d7-cbdd-4341-800a-c07d32e03be9)

2024-05-14 20:20 UTC, nickytonline requested changes
The height fix looks good on some of the larger screens, but some mid size screens have blank graphs. There are also hydration errors on smaller screens.

![CleanShot 2024-05-14 at 16 19 04](https://github.com/open-sauced/app/assets/833231/cd3df868-741b-4ba2-9f30-dc9b8588b13d)

2024-05-14 20:58 UTC, zeucapua commented
@nickytonline hydration errors only happen on dev. Using the deploy on mobile looks fine to me.

2024-05-14 21:10 UTC, bdougie approved these changes
🚀🚀🚀

2024-05-14 21:28 UTC, nickytonline commented
> @nickytonline hydration errors only happen on dev. Using the deploy on mobile looks fine to me. Also I'm getting the graph for mid size displays, I don't know how it isn't rendering like what you're showing.

K. If no one else is seeing what I’m seeing, let’s ship for now.

2024-05-14 21:28 UTC, nickytonline approved these changes
:shipit:

2024-05-14 22:15 UTC, BekahHW requested changes
I'm getting some shifting out of the graph border when changing the date filter.

https://github.com/open-sauced/app/assets/34313413/00a20eb3-7499-4246-9e9b-f55f6537a9ff

2024-05-14 22:20 UTC, jpmcb reviewed
cc @BekahHW - yeah, I see something very similar in the kubernetes/kubernetes repo when going to 90 days.

![Screenshot 2024-05-14 at 4 18 46 PM](https://github.com/open-sauced/app/assets/23109390/c7b60c2e-8170-468b-b003-8f1ded94a5fb)

Otherwise, looks incredible 🥇

2024-05-15 08:10 UTC, zeucapua commented
Tested on desktop (arc + safari) and iphone. Should be good now. There's a very small height shift going through different day range, but I think it's negligible enough to ship.
https://github.com/open-sauced/app/assets/20603494/687aee82-e083-4b7b-9a12-5d8cacc686c1

2024-05-15 12:31 UTC, bdougie commented
There is a small issue with avatar height for older users. Fine on [supabase](https://deploy-preview-3373--oss-insights.netlify.app/s/supabase/supabase), noticeable on [react-router](https://deploy-preview-3373--oss-insights.netlify.app/s/remix-run/react-router).

<img width="460" alt="Screenshot 2024-05-15 at 5 27 14 AM" src="https://github.com/open-sauced/app/assets/5713670/aeee8caa-3dec-42f1-9849-ff7dc0c57641">

2024-05-15 13:06 UTC, nickytonline commented
I've sorted the avatar resizing issue @bdougie with a temporary fix. It appears to be an issue with the avatar hover card component.

![CleanShot 2024-05-15 at 09 05 06](https://github.com/open-sauced/app/assets/833231/10c0fd8e-6d27-433c-a507-a3f8db226f22)

2024-05-15 13:12 UTC, bdougie approved these changes
Looks great. Let's merge this one and do a follow up fix for the avatar card later. I'd love to spin up a video in preparation for the React Conf keynote.

2024-05-15 13:14 UTC, BekahHW approved these changes

2024-05-15 13:18 UTC, isabensusan approved these changes
I'd say it's good to merge, but it'd be great to get a follow up PR to fix the chart bleeding
<img width="877" alt="image" src="https://github.com/open-sauced/app/assets/27322879/69cd82ab-a803-41d5-8344-5ccd4edd8736">

2024-05-15 13:19 UTC, merged