chore(next.config.js): rewrite image config
open-sauced/app pull request #3400
Opened 2024-05-16 14:11 UTC by sourabpramanik

## Description
This PR rewrites the deprecated image config to use remote images in the application

## Related Tickets & Documents

chore #3376

## Mobile & Desktop Screenshots/Recordings

None

## Steps to QA

None

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [ ] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?

2024-05-16 20:06 UTC, nickytonline requested changes
This works great @sourabpramanik. Just one change request. Thanks for the cleanup!

2024-05-16 20:06 UTC, nickytonline commented on next.config.js
> +      },
refactor (blocking): empty ports aren't necessary.

```suggestion
    remotePatterns: [
      {
        protocol: "https",
        hostname: "avatars.githubusercontent.com",
      },
      {
        protocol: "https",
        hostname: "images.unsplash.com",
      },
      {
        protocol: "https",
        hostname: "www.github.com",
      },
      {
        protocol: "https",
        hostname: "github.com",
      },
      {
        protocol: "https",
        hostname: "res.cloudinary.com",
      },
```

2024-05-17 02:08 UTC, nickytonline approved these changes
Thanks @sourabpramanik!

2024-05-17 13:12 UTC, BekahHW approved these changes

2024-05-17 13:38 UTC, merged