Feature: Track Repo Pages (Header)
open-sauced/app pull request #3728
Opened 2024-07-16 22:00 UTC by zeucapua

## Description

Implements PostHog captures throughout the repo pages' headers on both tabs. The events captured in this section are:
- "Add to Workspace": click button and confirm add on modal
- `<DayRangePicker>`: capture chosen range on value change
- `<LanguagePill>`: capture the repo language when going to the explore page 

## Related Tickets & Documents

Closes #3723 

## Mobile & Desktop Screenshots/Recordings

## Steps to QA
1. Go to any repo page (some repos might not have a language to click)
2. Interact with the listed components
3. Do the listed events
4. Check PostHog events (or the Repo Pages dashboard) to see if events are captured

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?

![steve-kornacki-news-gif-by-msnbc](https://github.com/user-attachments/assets/d508489f-169d-4680-a6db-6831ba690a2b)

2024-07-16 23:09 UTC, bdougie approved these changes

2024-07-17 00:00 UTC, nickytonline requested changes

2024-07-17 00:00 UTC, nickytonline commented on components/Repositories/AddToWorkspaceModal.tsx
> +    posthog.capture(`Repo Pages: added to ${workspaceId === "new" ? "a new" : "existing"} workspace`, {
refactor (blocking): prefer the `usePosthog` hook instead as we already have a [Posthog provider configured](https://github.com/open-sauced/app/blob/95774d898160e19a2d427b5dc4cd8d9474f625a0/pages/_app.tsx#L152-L162). See https://posthog.com/tutorials/single-page-app-pageviews and an example usage at https://github.com/open-sauced/app/blob/95774d898160e19a2d427b5dc4cd8d9474f625a0/components/ListHeader/list-header.tsx

2024-07-17 15:02 UTC, brandonroberts approved these changes

2024-07-17 16:15 UTC, nickytonline approved these changes
:shipit:

2024-07-17 16:23 UTC, merged