feat: add OSCR tooltip to user page
open-sauced/app pull request #3857
Opened 2024-08-05 18:31 UTC by zeucapua

## Description

Implements an `InfoTooltip` to the user page (`/u/[username]`) to explain what OSCR is.

## Related Tickets & Documents

Closes #3854 

## Mobile & Desktop Screenshots/Recordings

## Steps to QA

1. Go to any user page

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?

2024-08-05 18:37 UTC, nickytonline reviewed
The info tooltip works, but it's super small. It's hard to tell what it is as it looks like a circle with a small dot in it.

![CleanShot 2024-08-05 at 14 36 46](https://github.com/user-attachments/assets/2cd08093-7eb6-4e44-8fa9-6b662e659a6f)

2024-08-05 19:21 UTC, nickytonline requested changes

2024-08-05 19:21 UTC, nickytonline commented on components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
> +                <span className="flex gap-2 text-sm">
The info icon is larger now, but the text ends up being misaligned now.

![CleanShot 2024-08-05 at 15 20 25](https://github.com/user-attachments/assets/a0f44182-1223-49e4-84c7-de471183a4f7)

![CleanShot 2024-08-05 at 15 20 06](https://github.com/user-attachments/assets/b3366341-7349-4eba-97ed-4079bd1ec441)

2024-08-05 23:25 UTC, jpmcb approved these changes
Copy looks great!

2024-08-07 16:34 UTC, brandonroberts approved these changes

2024-08-07 16:43 UTC, nickytonline requested changes

2024-08-07 16:43 UTC, nickytonline commented on components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
> +                <span className="flex gap-2 text-sm">
It's still off, but I figured a way to have it bigger and line up properly.

For the OSCR set the JSX to:

```jsx
              <div>
                <span className="relative text-xs text-light-slate-11 flex gap-0.5 items-center">
                  <span>OSCR Rating</span>
                  <span className="text-sm grid place-content-center">
                    <InfoTooltip information="OSCR evaluates the engagement and impact of contributors across the entire open source ecosystem." />
                  </span>
                </span>
                <div className="flex mt-1 text-lg md:text-xl lg:text-2xl !text-black leading-none">
                  <OscrButton rating={contributor?.oscr} hideRating={!Boolean(user)} />
                </div>
              </div>
```

And for the other stats, add `flex-items center`, e.g.

```diff
              <div>
-                <span className="text-xs text-light-slate-11">PRs opened</span>
+                <span className="text-xs text-light-slate-11 flex items-center">PRs opened</span>

                {totalPrs ? (
                  <div className="flex mt-1 !text-lg md:!text-xl lg:!text-2xl !text-black !leading-none">
                    {totalPrs} PRs
                  </div>
                ) : (
                  <div className="mt-1">{DATA_FALLBACK_VALUE}</div>
                )}
              </div>
```

2024-08-08 19:07 UTC, nickytonline approved these changes
Approving after chatting about it in our 1:1 that you'll be making the suggested changes.

2024-08-08 21:52 UTC, merged