feat: update DevCard design
open-sauced/app pull request #3879
Opened 2024-08-07 01:42 UTC by zeucapua

## Description

Implements a new DevCard design that showcases OSCR and the user's contribution activity

## Related Tickets & Documents

Closes #3872 

## Mobile & Desktop Screenshots/Recordings

## Steps to QA
1. Go to a user's page and click the pizza icon beside their avatar
2. See the new design, pressing arrow keys or clicking to go to other DevCards

## Tier (staff will fill in)

- [ ] Tier 1
- [x] Tier 2
- [ ] Tier 3
- [ ] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?

![approve-love-it-gif-by-disney-channel](https://github.com/user-attachments/assets/c146f47d-27da-4fb5-b79c-7bf25f225449)

2024-08-10 01:08 UTC, nickytonline commented
It looks like your test fails as part of the regular test suite. The unit/component tests aren't aware of the env vars/creating a supabase client.

![image](https://github.com/user-attachments/assets/676c6a30-0fbf-4968-90f2-926638517662)

I don't think the tests ever passed locally. I got them to stop failing by adding the following to the vitest.config.ts. Add this property to the test section.

    env: {
      NEXT_PUBLIC_SUPABASE_URL: "https://test.supabase.co",
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "test-anon-key",
    },
so it becomes

import { fileURLToPath } from "url";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      components: fileURLToPath(new URL("./components", import.meta.url)),
      lib: fileURLToPath(new URL("./lib", import.meta.url)),
      helpers: fileURLToPath(new URL("./helpers", import.meta.url)),
      img: fileURLToPath(new URL("./img", import.meta.url)),
    },
  },
  test: {
    include: ["./**/*.test.ts", "./**/*.test.tsx"],
    globals: true,
    environment: "jsdom",
    env: {
      NEXT_PUBLIC_SUPABASE_URL: "https://test.supabase.co",
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "test-anon-key",
    },
  },
});
That said, I still think writing an E2E test instead would fit better or scope down the component test to a single dev card.

Having to load env vars for unit tests/component tests doesn't feel right. Typically, that'd be something you'd mock (supaseClient).

Right now with the fix above, the tests run now, but fail with

AssertionError: expected "spy" to be called with arguments: [ undefined ]

Received: 

  1st spy call:

  Array [
-   undefined,
+   "zeucapua",
  ]


Number of calls: 1

 ❯ components/organisms/DevCardCarousel/dev-card-carousel.test.tsx:28:26


⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[2/3]⎯

 FAIL  components/organisms/DevCardCarousel/dev-card-carousel.test.tsx > DevCardCarousel > when the user uses the arrow keys > when the user presses the left arrow key > should select the second card
AssertionError: expected "spy" to be called with arguments: [ undefined ]

Received: 

  1st spy call:

  Array [
-   undefined,
+   "zeucapua",
  ]


Number of calls: 1

 ❯ components/organisms/DevCardCarousel/dev-card-carousel.test.tsx:36:26
We can look at it Monday.

2024-08-12 13:22 UTC, nickytonline requested changes

2024-08-12 13:22 UTC, nickytonline commented on pages/u/[username]/card.tsx
> +            className="rounded-full w-10 h-10 grid place-content-center border hover:opacity-80 transition-all"
These changes are making the X logo too big.

**In this PR**

![CleanShot 2024-08-12 at 09 18 40](https://github.com/user-attachments/assets/f1d42ec7-4cce-4bc3-83f6-637f36b0bc3f)

**In Prod**

![CleanShot 2024-08-12 at 09 21 24](https://github.com/user-attachments/assets/fce3da13-b7cd-46b0-8a1d-d7a003bb483e)

2024-08-12 14:13 UTC, nickytonline requested changes

2024-08-12 14:13 UTC, nickytonline commented on pages/404.tsx
> +};
Refactor (blocking): `fetchApiData` handles all of this. The username should also be validated before making the call.

You can use `fetchApiData`'s pathValidator

```javascript
pathValidator: () => safeParse(GitHubUserNameSchema, username).success
```

You can update validation-schemas.ts with this:

```diff
- import { parse, pipe, string, uuid } from "valibot";
+ import { parse, pipe, regex, string, uuid } from "valibot";

export const parseSchema = parse;

export const UuidSchema = pipe(string(), uuid("The UUID is badly formatted."));
+ 
+ const GitHubUserNameSchema = pipe(
+   string(),
+   regex(/^[a-z\d](?:[a-z\d]|-(?=[a-z\d])){0,38}$/i, "The GitHub + username is invalid.")
+ );
```

2024-08-12 14:13 UTC, nickytonline commented on pages/404.tsx
> +      const cardData = await Promise.all(data.map((user) => fetchUserData(user.login)));
Not for this PR, but it might be good to have a call that gets the card data for all the users in one shot. Not sure how many you're requesting atm.

2024-08-12 14:13 UTC, nickytonline commented on pages/u/[username]/card.tsx
> +    if (!isValidUrlSlug(username)) {
You could used the suggested `GitHubUserNameSchema` up top here as well. `isValidUrlSlug` accepts underscores, but GitHub usernames do not allow for them.

2024-08-12 16:13 UTC, jpmcb commented
If we can move this forward as "good enough ™️ " to not block launch and fast follow with small style fixes or code cleanup, I'd say that'd be ideal.

2024-08-12 16:29 UTC, nickytonline commented
> If we can move this forward as "good enough ™️ " to not block launch and fast follow with small style fixes or code cleanup, I'd say that'd be ideal.

I'm going to go ahead and approve based on ☝🏻. Just have a fast follow for change requests that weren't made.

2024-08-12 16:30 UTC, nickytonline approved these changes
Approving to get this into the launch.

2024-08-12 16:38 UTC, BekahHW approved these changes
![Let's Go](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHhldWYyZnIwc3RhMGl1cWxhYmhhdW9jYThtYXh6Nng4ZjN6Nm9ubyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/dMsh6gRYJDymXSIatd/giphy.gif)

2024-08-12 16:48 UTC, merged