fix : resolve incorrect redirect to 404 page on search fields
open-sauced/app pull request #3959
Opened 2024-08-15 19:14 UTC by Mandeep56Singh

Closes #3949

## Description

The search functionality in explore was redirecting users to a 404 error page
when they entered a query. This was caused by incorrect URL routing
in the search handle function

This commit fixes the routing logic by ensuring the search terms
are correctly encoded, thus preventing the 404 error. 

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

https://github.com/user-attachments/assets/13ba7163-a350-4ace-8571-163aea59db28

## Steps to QA

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [ ] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?

Really sorry due to prettier some lines sorted unintentionally

2024-08-20 20:00 UTC, brandonroberts approved these changes
Thanks! 🍕

2024-08-20 21:21 UTC, jpmcb approved these changes

2024-08-20 21:45 UTC, brandonroberts requested changes

2024-08-20 21:45 UTC, brandonroberts commented on components/organisms/Repositories/repositories.tsx
>        return router.push(`/${topic}/${toolName}`);
```suggestion
       return router.push(`/explore/topic/${topic}/${toolName}`);
```

2024-08-22 10:43 UTC, Mandeep56Singh commented
@brandonroberts  sorry it  took look to apply changes, I am quite knew to open source, So I didn't knew what to do.

2024-08-22 16:53 UTC, brandonroberts commented
@Mandeep56Singh no problem, thanks

2024-08-22 16:53 UTC, brandonroberts approved these changes

2024-08-22 17:06 UTC, merged