chore: Use DbUser for /contributor/search endpoint
open-sauced/app pull request #3989
Opened 2024-08-19 20:46 UTC by jpmcb

## Description

Followup to: https://github.com/open-sauced/api/pull/1039

> [!WARNING]
> Note: this should go in alongside the above API change. The API for `v2/contributor/search` will be returning `DbUser` (which includes the OSCR) now

## Related Tickets & Documents

Related to work in: https://github.com/open-sauced/app/issues/3859 - cc @zeucapua this is relevant to what you're working on with the OSCR in contributor search

## Mobile & Desktop Screenshots/Recordings

Things look good!

![Screenshot 2024-08-19 at 2 45 47 PM](https://github.com/user-attachments/assets/676e58aa-4cbb-4314-8a4c-0d04cd398189)

## Steps to QA

1. Run API locally (or wait for the API changes to land on beta)
2. Run App locally
3. Inspect workspaces table, contributor cards, and repo pages contributors still all work

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

2024-08-19 21:44 UTC, zeucapua requested changes
As noted on https://github.com/open-sauced/api/pull/1039#discussion_r1722379343, the `DbUser` type returned should have a `total_contributions` field for the `ContributorsTable` component. 

Also multiple stories for the changed components are failing due to the mock user doesn't match the new type. Use one of the objects from the `STUB_DATA` array in the `/components/organisms/DevCardCarousel/stubData.ts` file as a substitute. There will be extra fields inside that should be deleted, but they should be clear with a type checker.

2024-08-19 22:53 UTC, jpmcb commented
@zeucapua - I think I got the types ironed out: the new type I added is essentially a superset type of `DbUser` (which includes all the fields from the user entity alongside the devstats from the API). I wonder if in the future we should unify these types - problem for future us!

2024-08-20 15:57 UTC, brandonroberts commented
Contributor data on the explore page is missing

https://deploy-preview-3989--oss-insights.netlify.app/explore/topic/typescript/contributors/filter/recent?range=30

![image](https://github.com/user-attachments/assets/28f23a86-7330-4706-bfee-06dcd7304d55)

2024-08-20 17:00 UTC, jpmcb commented
>Contributor data on the explore page is missing https://deploy-preview-3989--oss-insights.netlify.app/explore/topic/typescript/contributors/filter/recent?range=30

@brandonroberts - note my warning: the deploy preview won't work until https://github.com/open-sauced/api/pull/1039 goes in (since this uses those new types in the `v2/contributors/search` endpoint.

2024-08-20 17:01 UTC, brandonroberts commented
Thanks 🤦

2024-08-21 15:07 UTC, zeucapua approved these changes

2024-08-21 15:43 UTC, jpmcb commented
API changes cut into beta, deploy preview is live with changes: https://deploy-preview-3989--oss-insights.netlify.app

![Screenshot 2024-08-21 at 9 43 33 AM](https://github.com/user-attachments/assets/f417ae7b-92cc-4460-9ca3-721db3093618)

2024-08-21 15:59 UTC, merged