fix: Prevent OSCR score from popping out of dev card with long usernames
open-sauced/app pull request #4010
Opened 2024-08-22 17:51 UTC by Mandeep56Singh

## Description

This PR addresses the bug where a long username in a developer card causes the OSCR score to overflow and pop out of the card's boundary while also address related to it.

- resolve Hydaration error in Devcard component by using useEffect and useState for props.isLoading.
- fix styling in front view of card by limiting its width,text-center and wrapping
- fix styling in back view of card by truncate tailwind utility
- increase font size of oscr  limit  from 0.5 rem to 0.7rem to make it visible

closes #3981 

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings
### Front view  at max username length
![Screenshot (438)](https://github.com/user-attachments/assets/8ec58bbb-985a-4e76-aeb7-25404dc5e098)

### Back view at lengthy username
![Screenshot (435)](https://github.com/user-attachments/assets/198ee77d-a2bd-4a6e-9d14-813a2c1ea363)

### username in next line 
![Screenshot (437)](https://github.com/user-attachments/assets/85233e97-5fa0-47ce-a0bd-799c75ec119f)

## Steps to QA

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [ ] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?

2024-08-26 14:59 UTC, nickytonline commented
I was going to suggest not showing the OSCR on the back of the card since it's already on the front and leave as much real estate for the username. Thoughts @brandonroberts @zeucapua @isabensusan?

2024-08-26 18:03 UTC, Mandeep56Singh commented
@brandonroberts  actually I had hydration error while solving this issue, To my understanding It was due to props.isLoading. 
However I have fixed it. I would require your assistance on this.

2024-08-26 20:42 UTC, brandonroberts commented
> I was going to suggest not showing the OSCR on the back of the card since it's already on the front and leave as much real estate for the username. Thoughts @brandonroberts @zeucapua @isabensusan?

I agree

2024-08-27 18:17 UTC, BekahHW commented
@nickytonline we have it on the back of the card like that to provide more context - it's out of 300. I think if we remove it here we need to have it referenced somewhere else on the card.

2024-08-27 18:35 UTC, nickytonline commented
> @nickytonline we have it on the back of the card like that to provide more context - it's out of 300. I think if we remove it here we need to have it referenced somewhere else on the card.

Maybe we move it somewhere else on the card on the back. It looks nice to see a full username on the back instead of it being cut off.

2024-08-28 06:47 UTC, Mandeep56Singh commented
@BekahHW we can it in front, we just need to add a line displaying 
there are various ways for it 
 
 ### we can display the out of message under score, but when we have long username ( 2 lines ) then it will look ugly
![Screenshot (442)](https://github.com/user-attachments/assets/218a4d88-a2d2-4613-8b5d-fe6eb2edbe1f)

### displaying it with OSCR score
![Screenshot (440)](https://github.com/user-attachments/assets/0ded8462-7a53-4ff8-a7b4-ae498d1b2334)

### I found this good, since we don't really need "score" in text as OSCR itself is rating 
![Screenshot (443)](https://github.com/user-attachments/assets/adc53500-3d84-43fd-b62c-989688992ca2)

2024-08-28 07:20 UTC, Mandeep56Singh commented
@nickytonline  full username on the back can take a lot of space as longest username can be of 39 characters, it would require two lines. I think  adding  more statistics on the back side, so user can know more about the person. We can remove the username, profile pic and oscr score from back. 

we have different option for it.
###  added new statistics and remove header of back view
![Screenshot (444)](https://github.com/user-attachments/assets/0d93a45f-8f05-49b3-985a-08355338da0b)

### this looks good
![Screenshot (445)](https://github.com/user-attachments/assets/e1bb3eb7-cbdb-428e-a695-92f0941a9f7b)

what are your thoughts ?

2024-08-28 22:19 UTC, BekahHW commented
I would prefer the original fix here. It solves the initial problem without a redesign. Maybe @isabensusan has thoughts.

2024-09-03 15:43 UTC, isabensusan commented
@Mandeep56Singh I also prefer the original original fix! Let's truncate longer user names

2024-09-03 19:19 UTC, Mandeep56Singh commented
@isabensusan  ok, the front view also have overflowing problem, the longest github username can be 39 characters long, so it will be two lines, I thought of centering the username. 
what you are your thoughts ?
thanks.

![Screenshot (437)](https://github.com/user-attachments/assets/85233e97-5fa0-47ce-a0bd-799c75ec119f)
![Screenshot (438)](https://github.com/user-attachments/assets/8ec58bbb-985a-4e76-aeb7-25404dc5e098)

2024-09-11 15:39 UTC, isabensusan commented
hey @Mandeep56Singh ! Yes, centering looks good  :)

2024-09-11 16:20 UTC, Mandeep56Singh commented
> hey @Mandeep56Singh ! Yes, centering looks good :)

Thanks a lot, @isabensusan! I really appreciate the feedback. 
Looking forward to making more contributions to OpenSauced!"

2024-09-17 19:44 UTC, isabensusan approved these changes
Design wise, looks good to me!

2024-09-17 20:20 UTC, brandonroberts submitted a review, later dismissed

2024-09-17 20:20 UTC, brandonroberts commented on components/molecules/DevCard/dev-card.tsx
> +  useEffect(() => {
We have a hook for this already named `useHasMounted` that can be used instead.

```ts
import { useHasMounted } from "lib/hooks/useHasMounted";

const hasMounted = useHasMounted();
```

2024-09-18 12:48 UTC, nickytonline requested changes
Works great @Mandeep56Singh! One small change request and this is good to go.

![CleanShot 2024-09-18 at 08 41 44](https://github.com/user-attachments/assets/8a0366b7-120f-4515-8770-2e61fb77f0fe)

2024-09-18 12:48 UTC, nickytonline commented on components/molecules/DevCard/dev-card.tsx
>                <p className="-pl-4 justfy-self-end text-sm flex gap-0.5">
Center the text. Also it looked like it was never self justifying to the end.

```suggestion
              <p className="-pl-4 justify-self-end items-center text-sm flex gap-0.5">
```

2024-09-18 15:51 UTC, nickytonline approved these changes
Thanks for making the changes @Mandeep56Singh! 🚢

2024-09-19 12:58 UTC, brandonroberts approved these changes

2024-09-19 13:24 UTC, nickytonline commented
When you have a chance @zeucapua, we need your approval. Thanks!

2024-09-19 13:57 UTC, merged