Feat: Add contributor's insight on the workspace.
open-sauced/app pull request #4060
Opened 2024-08-28 18:17 UTC by oyezaheer

Fixes #3948

![Screenshot 2024-08-28 234402](https://github.com/user-attachments/assets/f33daa48-6a12-4d3c-8bb2-7771fc63a0d7)

2024-08-28 21:17 UTC, jpmcb commented
Thanks for this contribution @oyezaheer - this looks to contain changes from one of your previous PRs. Please get the latest changes from the `beta` branch and clean this up and we'll move this forward.

Also looks like the Playwright tests are failing:

```

./pages/workspaces/[workspaceId]/activity.tsx:133:12
Type error: Type '{ workspace: Workspace; }' is missing the following properties from type 'WorkspaceHeaderProps': title, url

  131 |       >
  132 |         <div className="px-4 py-8 lg:px-16 lg:py-12">
> 133 |           <WorkspaceHeader workspace={workspace} />
      |            ^
  134 |           <div className="grid sm:flex gap-4 pt-3 border-b">
  135 |             <WorkspacesTabList workspaceId={workspace.id} selectedTab={"activity"} />
  136 |           </div>
```

2024-08-29 12:12 UTC, nickytonline commented
> Thanks for this contribution @oyezaheer - this looks to contain changes from one of your previous PRs. Please get the latest changes from the `beta` branch and clean this up and we'll move this forward.
> 
> Also looks like the build and Playwright tests are failing. Please make sure everything builds before requesting review.
> 
> ```
> 
> ./pages/workspaces/[workspaceId]/activity.tsx:133:12
> Type error: Type '{ workspace: Workspace; }' is missing the following properties from type 'WorkspaceHeaderProps': title, url
> 
>   131 |       >
>   132 |         <div className="px-4 py-8 lg:px-16 lg:py-12">
> > 133 |           <WorkspaceHeader workspace={workspace} />
>       |            ^
>   134 |           <div className="grid sm:flex gap-4 pt-3 border-b">
>   135 |             <WorkspacesTabList workspaceId={workspace.id} selectedTab={"activity"} />
>   136 |           </div>
> ```

I updated the branch and the changes from the previous PRs are gone.

2024-08-29 12:29 UTC, nickytonline requested changes

2024-08-29 12:29 UTC, nickytonline commented on components/Workspaces/WorkspaceHeader.tsx
>        <div className="flex gap-2 justify-end">
refactor (blocking): On smaller screens, the feature is not responsive. It causes other buttons to go off screen and will cause the layout for any page using the WorkspacesHeader to break.

![CleanShot 2024-08-29 at 08 22 30](https://github.com/user-attachments/assets/8762e1af-0b95-474a-a431-3fbe9306d8d7)

Adding flex wrap should sort it out. 👇

![CleanShot 2024-08-29 at 08 27 52](https://github.com/user-attachments/assets/6183cf81-560a-45c2-b937-1a7924331b15)

```suggestion
      <div className="flex gap-2 justify-end flex-wrap">
```

2024-08-29 16:11 UTC, nickytonline approved these changes
Thanks @oyezaheer! :shipit:

2024-08-29 16:35 UTC, brandonroberts approved these changes
🍕

2024-08-29 16:42 UTC, merged