feat: use `SplitButton` for repo page Add Workspace buttons
open-sauced/app pull request #4062
Opened 2024-08-28 21:32 UTC by zeucapua

## Description

Implements the `SplitButton` component to combine the 'Add to Workspace' and 'Create Workspace from SBOM' buttons on desktop. Adds a new optional 'icon' prop to `SplitButton`. 

## Related Tickets & Documents

Closes #3942 

## Mobile & Desktop Screenshots/Recordings

https://github.com/user-attachments/assets/2db7c732-d72a-48de-8eb7-76414b81734e

## Steps to QA

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?

2024-08-28 22:08 UTC, nickytonline requested changes
Not specific to this PR but since it's the first usage of the split button component, the shifting should get sorted out either in a separate PR or this one.

2024-08-28 22:08 UTC, nickytonline commented on pages/s/[org]/[repo]/index.tsx
> +                    <SplitButton
The split button works, but it looks like now that it's being used, it causes some layout shift.

![CleanShot 2024-08-28 at 18 05 54](https://github.com/user-attachments/assets/8ab0e0db-bf4e-4b76-82ea-6b4e3b4e474c)

2024-08-29 17:22 UTC, zeucapua commented
It shouldn't shift now; aligned the dropdown menu to "end", bringing it more towards the center of the page

![image](https://github.com/user-attachments/assets/73e39bac-0a67-4f8f-877a-1b0131dc0997)

2024-08-29 18:37 UTC, brandonroberts approved these changes

2024-08-29 18:57 UTC, nickytonline requested changes
It's line up now component wise, but there is still some side shifting. Happy to pair if you want. We have our sync now anyway.

![CleanShot 2024-08-29 at 14 51 55](https://github.com/user-attachments/assets/1e353ee0-a434-47f9-940f-f8307a6e729f)

2024-08-30 18:01 UTC, zeucapua commented
Looks like under the hood, radix uses the `react-remove-scroll` package to remove scrolling when the Dropdown/SingleSelect is opened. The fix to keep the scroll is to set the prop `modal={false}` on the root components.

2024-08-30 20:29 UTC, nickytonline approved these changes
Works great! Thanks @zeucapua! 🚢 

![CleanShot 2024-08-30 at 16 29 13](https://github.com/user-attachments/assets/d4cf301f-89ac-470f-9bfd-d03488223455)

2024-08-30 21:10 UTC, merged