Chore add eslint jsx a11y package
open-sauced/app pull request #4118
Opened 2024-09-20 20:45 UTC by FatumaA

## Description

This PR adds the [eslint jsx a11y plugin](https://www.npmjs.com/package/eslint-plugin-jsx-a11y) to the project.

## Related Tickets & Documents

Fixes #2264 

## Mobile & Desktop Screenshots/Recordings

N/A

## Steps to QA

1. Run `npx eslint .` at root of project
2. See the accessibility issues show up as warnings instead of errors

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [ ] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?

![A GIF of a man in a black suit coat and a gray inner shirt is pulling his sleeves then flexing his collar](https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExNG5sdmF4aWp6eTg0bWJvODhpNWdlamVvZ3U1NzRxZzJuenlxbmp6ZCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/65Bfas6vezOyRUyRn7/giphy.webp)

2024-09-21 08:21 UTC, nickytonline commented
@FatumaA, thanks for the PR! This will be a great first step in sorting out some accessibility issues mentioned in the associated issue.

For the new rules, there's no need to explicitly set all the rules to warn. Only, set the rules to warn that currently cause the build to fail.

I believe most of the issues are `<div>`s with 'onClick`s in JSX, i.e. `jsx-a11y/no-noninteractive-element-to-interactive-role` which also causes this rule to fail, `jsx-a11y/click-events-have-key-events`.

From there, as discussed we can tackle those issues one by one, and once they're all sorted, we can remove all the rules that were set to warn so they can error by default, i.e. #4110

2024-09-24 17:19 UTC, FatumaA commented
I've removed the rules that did not cause errors when running `npx eslint .` in the  project root. I left about 10 rules that were causing errors.

2024-09-24 18:08 UTC, nickytonline approved these changes
Thanks for this @FatumaA! Looking forward to making the app more accessible!

2024-09-24 18:13 UTC, nickytonline requested changes
Looks like some more rules need warnings still to get the build to pass.

2024-09-24 18:13 UTC, nickytonline commented on .eslintrc.json
> +    "jsx-a11y/iframe-has-title": "warn",
Looks like these rules need warnings still as well.

```suggestion
    "jsx-a11y/iframe-has-title": "warn",
    "jsx-a11y/no-noninteractive-tabindex": "warn",
    "jsx-a11y/anchor-is-valid": "warn",
    "jsx-a11y/no-noninteractive-element-interactions": "warn",
    "jsx-a11y/interactive-supports-focus": "warn",    
```

2024-09-24 20:28 UTC, FatumaA commented
I should have run the build locally 🤦🏾‍♀️

2024-09-24 20:58 UTC, nickytonline approved these changes
:shipit:

2024-09-24 23:27 UTC, zeucapua approved these changes

2024-09-24 23:33 UTC, merged